server {
    listen 5173;
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/listings {
        proxy_pass http://marketplace:5003/api/listings;
        proxy_set_header Host $host;
    }

    location /api/orders {
        proxy_pass http://marketplace:5003/api/orders;
        proxy_set_header Host $host;
    }

    location /api/valuations {
        proxy_pass http://marketplace:5003/api/valuations;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://logistics:5002/api/;
        proxy_set_header Host $host;
    }
}
